data:
 clinical_path: "/home/silvia.collicelli/data/controlled_dataset_metadata.parquet"
 folder_path: "/home/silvia.collicelli/data/Dataset"

seed: 0
augmentation: "flip+rotation+jitter"

model: 
 criterion: "CrossEntropyLoss"
 optimizer: Adam
 scheduler: "ReduceLROnPlateau"

k_folds: 5

early_stopping:
 do_it: False
 patience: 5
 min_delta: 0.001