data:
 clinical_path: "C:\\Users\\utente\\Documents\\UNI\\MAGISTRALE\\tesi\\naive_baseline\\raw_dataset\\artifacts\\clinical_case_metadata.parquet"
 folder_path: "C:\\Users\\utente\\Documents\\UNI\\MAGISTRALE\\tesi\\naive_baseline\\raw_dataset\\artifacts\\Dataset"

seed: 0
augmentation: "flip+rotation+jitter"

model: 
 criterion: "CrossEntropyLoss"
 optimizer: Adam
 scheduler: "ReduceLROnPlateau"