data:
 clinical_path: "/home/silvia.collicelli/data/controlled_dataset_metadata.parquet"
 folder_path: "/home/silvia.collicelli/data/Dataset"

early_stopping:
 patience: 5
 min_delta: 0.001

batch_size: 64
epochs: 15
k_fold: 5
seed: 0
device: str(device)
augmentation: "flip+rotation+jitter"

model: 
 last_leyer: "denseblock4"
 criterion: "CrossEntropyLoss"
 optimizer: Adam
 scheduler: "ReduceLROnPlateau"