program: main.py

method: bayes

metric:
 name: val_loss
 goal: minimize

parameters: 

 early_stopping.patience: 
  value: 5
 early_stopping.min_delta:
  value: 0.001

 lr_blocks:
  min: 1e-5
  max: 1e-3 
 lr_classifier:
  min: 1e-4
  max: 1e-2

 freeze_strategy:
  values: ["classifier_only", "last_block", "two_last_blocks"]

 batch_size: 
  values: [8, 16, 32]

 epochs: 
  values: [10, 15, 20]

 k_fold: 
  value: 5