command:
 - .venv/bin/python
 - main.py
 - ${args}

project: first_sweep_project

method: bayes

metric:
 name: val_loss
 goal: minimize

parameters: 

 lr_blocks:
  distribution: uniform
  min: 1e-5
  max: 1e-3 

 lr_classifier:
  distribution: uniform
  min: 1e-4
  max: 1e-2

 freeze_strategy:
  values: ["classifier_only", "last_block", "two_last_blocks"]
  
 dropout_rate:
  values: [0.0, 0.2, 0.3, 0.5]

 batch_size: 
  values: [8, 16, 32]

 epochs: 
  value: 20