program: dsmil.py
project: DSMIL_first
method: grid
metric:
 name: val_loss
 goal: minimize

parameters: 

 fold:
  values: [0, 1, 2, 3, 4]
  
 numb_frames:
  values: [8, 16, 32, 64, 128]
  
 l_rate:
  values: [1e-3, 1e-4, 1e-5]

 batch_size: 
  values: [32, 64]

 epochs: 
  value: 1000

 att_dim:
  values: [64, 128, 256]

 nonlq:
  values: [False, True]
  
 nonlv: 
  values: [1, 0.0, 0.3]
