program: dsmil/dsmil.py
project: DSMIL_sweep
method: grid
metric:
 name: f1_score
 goal: maximize

#runna questa conf per più epoche
#non linear v,q e dropout, ma learning rate più piccolo -> vedi se diminuisce la variability
#poi scegli ultimo sweep e fai ultimo sweep su numb_frames, batch size
parameters: 

 fold:
  values: [0, 1, 2, 3, 4]
  
 numb_frames:
  value: 16
  #values: [8, 16, 32, 64, 128]
  
 l_rate:
  #value: 1e-4
  values: [1e-4, 5e-5, 1e-5]

 batch_size: 
  value: 64
  #values: [32, 64]

 epochs: 
  value: 1000

 att_dim:
  value: 256
  #values: [64, 128, 256]

 nonlq:
  value: True
  #values: [False, True]
  
 nonlv: 
  #value: 1
  values: [0.1, 0.2]
