data:
 #clinical_path: "/home/silvia.collicelli/data/controlled_dataset_metadata.parquet"
 #folder_path: "/home/silvia.collicelli/data/Dataset"
 #frames_folder: "/home/silvia.collicelli/frames32"
 frames_folder: "C:\\Users\\utente\\Documents\\UNI\\MAGISTRALE\\tesi\\raw_dataset\\artifacts\\frames32"
 clinical_path: "C:\\Users\\utente\\Documents\\UNI\\MAGISTRALE\\tesi\\raw_dataset\\artifacts\\clinical_case_metadata.parquet"
 folder_path: "C:\\Users\\utente\\Documents\\UNI\\MAGISTRALE\\tesi\\raw_dataset\\artifacts\\Dataset"

seed: 0
k_folds: 5
augmentation: "flip+rotation+jitter"

model: 
 criterion: "CrossEntropyLoss"
 optimizer: Adam
 scheduler: "ReduceLROnPlateau"


early_stopping:
 do_it: False
 patience: 5
 min_delta: 0.001