program: main.py

project: baseline_full_sweep
#name: fixed_lr_values

method: grid

metric:
 name: val_loss
 goal: minimize

#tot of sweep configurations: 80
parameters: 

 fold:
  values: [0, 1, 2]
  
 lr_blocks:
  values: [1e-4, 1e-5]

 lr_ratio:    #to have lr_classifier always bigger than lr_blocks, I fix the ratio between them, so if lr_blocks=0.001 and lr_ratio=5, then lr_classifier=0.005
  value: 10

 freeze_strategy:
  values: ["classifier_only", "last_block"]   #try without two_last_blocks
  
 dropout_rate:
  values: [0.0, 0.3]

 num_frames:
  value: 32

 batch_size: 
  value: 64

 epochs: 
  value: 40