data:
 #features_path: "/home/silvia.collicelli/project/embeddings/features"
 #labels_path: "/home/silvia.collicelli/project/embeddings/labels"
 #root_dir: "/home/silvia.collicelli/data/Dataset"
 #annotations_file: "/home/silvia.collicelli/data/controlled_dataset_metadata.parquet"
 features_path: "C:\\Users\\utente\\Documents\\UNI\\MAGISTRALE\\tesi\\raw_dataset\\artifacts\\embeddings\\features"
 labels_path: "C:\\Users\\utente\\Documents\\UNI\\MAGISTRALE\\tesi\\raw_dataset\\artifacts\\embeddings\\labels"
 root_dir: "C:\\Users\\utente\\Documents\\UNI\\MAGISTRALE\\tesi\\raw_dataset\\artifacts\\Dataset"
 annotations_file: "C:\\Users\\utente\\Documents\\UNI\\MAGISTRALE\\tesi\\raw_dataset\\artifacts\\clinical_case_metadata.parquet"


k_folds: 5
seed: 0
early_stopping:
 do_it: False
 patience: 5
 min_delta: 0.001